# Dependencies
gems:
  - jemoji
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

title: The Site of Jonas
description: My personal GitHub page, where I present (to me) interesting stuff. Maybe you'll like it too!<br/><br/> Powered by [Jekyll](http://jekyllrb.com/) and [Hyde](http://hyde.getpoole.com/).
tagline: Source of sorcery
baseurl: "/"

permalink: /:year/:month/:day/:title.html

paginate: 5

url: "https://jonasws.github.io"
timezone: Europe/Oslo
